import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav
          style={{
            borderBottom: "1px solid #ddd",
            padding: "12px 24px",
            backgroundColor: "#2b3640",
            display: "flex",
            gap: 0,
            alignItems: "center",
          }}
        >
          <Link
            href="/"
            style={{
              fontSize: 14,
              fontWeight: 400,
              textDecoration: "none",
              color: "#ffffff",
              padding: "0 16px",
            }}
          >
            CMS Dashboard
          </Link>
          <div
            style={{
              width: 1,
              height: 16,
              backgroundColor: "rgba(255, 255, 255, 0.3)",
            }}
          />
          <Link
            href="/modules-browser"
            style={{
              fontSize: 14,
              fontWeight: 400,
              textDecoration: "none",
              color: "#ffffff",
              padding: "0 16px",
            }}
          >
            Modules Browser
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
