import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TopNavStack from "../components/cms/TopNavStack";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          style={{
            marginTop: "5%",
            marginLeft: "5%",
            marginRight: "5%",
            boxSizing: "border-box",
          }}
        >
          <TopNavStack />
          <div
            style={{
              marginTop: "5%",
              marginBottom: "5%",
            }}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
